### ISSUE TITLE
How to save and load models

### ISSUE THREAD

**Issue by ctgu-huamei** [tanjuntao/constrained-seed-KMeans#1]
I want to save ConstrainedSeedKMeans model. In this way, when processing new data, I can directly load the model to predict.
What should I do?

**Comment by tanjuntao** [comment]
Hi, thanks for your attention for this repo. You can simply use Python's build-in `pickle` module to dump the `ConstrainedSeedKMeans` object and then load it back. For example,

``` python
import pickle

seed_kmeans = ConstrainedSeedKMeans(n_clusters=3, n_init=10, verbose=False)
seed_kmeans.fit(X, Y)
# save the model
with open('seed_kmeans.model', 'wb') as f:
    pickle.dump(seed_kmeans, f)

# load the model back
with open('seed_kmeans.model', 'rb') as f:
    seed_kmeans = pickle.load(f)
